version: "2"

linters:
  enable:
    - errcheck
    - wrapcheck
    - errorlint
    - gocritic
    - staticcheck
    - govet
    - revive
    - misspell
    - godot
    - gosec
  settings:
    godot:
      scope: declarations
    gocritic:
      enabled-tags:
        - performance
        - style
        - diagnostic
    revive:
      rules:
        - name: exported
    wrapcheck:
      ignore-sig-regexps:
        - \.Errorf\(
    gosec:
      excludes:
        - G304

formatters:
  enable:
    - gofmt
    - goimports
