version: "2"

linters:
  enable:
    - errcheck
    - wrapcheck
    - errorlint
    - gocritic
    - staticcheck
    - govet
    - revive
    - gofmt
    - goimports
    - misspell
    - godot
    - gosec

linters-settings:
  godot:
    scope: comments
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
  revive:
    rules:
      - name: exported
  wrapcheck:
    ignoreSigs:
      - .Errorf(
  gosec:
    excludes:
      - G304
